accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views


urlpatterns = [
    url(r"^signin/$", views.signin, name="signin"),
    url(r"^password_reset/$",
        auth_views.password_reset,
        {"template_name": "accounts/password_reset.html",
         "email_template_name": "accounts/password_reset_email.html",
         "subject_template_name": "accounts/password_reset_subject.txt",
         "post_reset_redirect": "password_reset/done/"},
        name="password_reset"),
    url(r"^password_reset/done/$",
        auth_views.password_reset_done,
        {"template_name": "accounts/password_reset_done.html"},
        name='password_reset_done'),
    url(r"^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$",
        auth_views.password_reset_confirm,
        {"template_name": "accounts/password_reset_confirm.html"})
]

custom_django_auth_system/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('hello.urls', namespace='hello')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', admin.site.urls),
]

hello/urls.py
from django.conf.urls import url

from hello.views import HomePageView, AboutUsPageView


urlpatterns = [
    url(r"^$", HomePageView.as_view(), name="index"),
    url(r"^about-us/$", AboutUsPageView.as_view(), name="about_us"),
]

accounts/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

hello/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import redirect
from django.contrib.auth.views import login as django_login

from django.conf import settings


def signin(request):
    if request.user.is_authenticated():
        return redirect(settings.LOGIN_REDIRECT_URL)
    return django_login(request, template_name='accounts/signin.html')

hello/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView


class HomePageView(LoginRequiredMixin, TemplateView):
    template_name = 'hello/index.html'


class AboutUsPageView(LoginRequiredMixin, TemplateView):
    template_name = 'hello/about.html'

accounts/templates/accounts/password_reset.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Custom Django Auth System</title>
</head>
<body>
    <div id="signin-page">
        {% block header %}
            <div class="page-head">
                <h1>Custom Django Auth System</h1>
            </div>
        {% endblock header %}
        <p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>

        <form method="post">
            {% csrf_token %}
            {{ form.email.errors }}
            <p>
                <label for="id_email">Email address:</label>
                {{ form.email }}
                <input type="submit" value="Reset my password" />
            </p>
        </form>
    </div>
</body>
</html>

accounts/templates/accounts/password_reset_done.html
<p>password reset done</p>

accounts/templates/accounts/signin.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Custom Django Auth System</title>
</head>
<body>
    <div id="signin-page">
        {% block header %}
            <div class="page-head">
                <h1>Custom Django Auth System</h1>
            </div>
        {% endblock header %}
        <form id="login_form" method="post" action="/login/">
            {% csrf_token %}
            <div class="credentials">
                <label>Username:</label>
                <input type="text" name="username" id="username"/>
            </div>
            <div class="credentials">
                <label>Password:</label>
                <input type="password" name="password" id="password"/>
            </div>
            <input type="submit" name="submit" id="login_button" value="Login" />
            <input type="hidden" name="next" value="{{ next }}" />
            <a href="{% url 'accounts:password_reset' %}">Password reset</a>
        </form>
    </div>
</body>
</html>

hello/templates/hello/about.html
<h3>You are viewing the 'About Us' page.</h3>
<a href="{% url 'hello:index' %}">Index page</a>

hello/templates/hello/index.html
<h2>Hello, Welcome to the site.</h2>
<h3>You are viewing the 'Index' page.</h3>
<a href="{% url 'hello:about_us' %}">About Us</a>